#! /bin/bash

day=${1:-1}

if [ ! -d "adventOfCode/day$day" ]; then
    mkdir "adventOfCode/day$day"
fi
cd "adventOfCode/day$day"

if [ ! -f "main.py" ]; then
cat > "main.py" <<- EOM
import sys

def part1(arr):
    return

def part2(arr):
    return

if __name__ == "__main__":
    with open(sys.argv[1], "r") as f:
        arr = f.read().splitlines()

        print(part1(arr))
        print(part2(arr))
EOM
fi

touch "input.txt"
touch "sample.txt"