#! /bin/bash

day=${1}

cd "adventOfCode"

if [ -z "$day" ]; then
    # If no day is given, generate next day
    for i in {1..25}
    do
        if [ ! -d "day$i" ]; then
            day=${i}
            break
        fi
    done
fi
echo "Generating day $day"
if [ ! -d "day$day" ]; then
    mkdir "day$day"
fi
cd "day$day"

if [ ! -f "main.ipynb" ]; then
    cp ../base.ipynb main.ipynb
fi

touch "input.txt"
touch "sample.txt"

until $(curl --output input.txt --silent --fail https://adventofcode.com/2021/day/$day/input -H @../../.cookie.txt); do
    sleep 30
done