#! /bin/bash

day=${1:-1}
input=${2:-"input.txt"}

cd "adventOfCode/day$day"
if [ ! -f "main.py" ]; then
    files=( *.ipynb )
    echo "Running notebook $files on day $day with $input"
    poetry run ipython -c "%run $files" $input
else
    echo "Running day $day with $input"
    eval "poetry run python main.py $input"
fi
